In [1]:
from tensorflow.keras.models import load_model
import os
from tensorflow.keras.layers import Average
from tensorflow.keras.models import Model

In [2]:
print("Files in the directory:", os.listdir())

Files in the directory: ['aaaaaa.ipynb', 'best_acc_v01.ckpt.weights.h5', 'best_acc_v02.ckpt.weights.h5', 'Circle_Equal_Parts.py', 'Circle_Ratio_Parts.py', 'CNN.h5', 'CNN.zip', 'CSV_FILES.zip', 'DTC.pkl', 'HEATMAP_ConfusionMatrix.png', 'imp_components', 'KNeighborsClassifier.pkl', 'LSTM.h5', 'minorproject.ipynb', 'minorproject0.ipynb', 'minorproject_new.ipynb', 'mitbih_test.csv', 'mitbih_train.csv', 'model_1.zip', 'model_2.zip', 'project1.ipynb', 'project2.ipynb', 'project3.ipynb', 'ptbdb_abnormal.csv', 'ptbdb_normal.csv', 'Sequential.h5', 'svc_model.pkl', 'test_csv.zip', 'train_csv.zip']


In [3]:
from tensorflow.keras.models import load_model

# Try to load the model
try:
    model = load_model('CNN.h5')
    print("The file contains the entire model (architecture + weights).")
except ValueError:
    print("The file contains only weights or is not a valid Keras model file.")

The file contains the entire model (architecture + weights).


In [4]:
from tensorflow.keras.models import load_model

# Try to load the model
try:
    model = load_model('LSTM.h5')
    print("The file contains the entire model (architecture + weights).")
except ValueError:
    print("The file contains only weights or is not a valid Keras model file.")

The file contains the entire model (architecture + weights).


In [5]:
cnn_model = load_model('CNN.h5')
lstm_model = load_model('LSTM.h5')

In [6]:
cnn_output = cnn_model.output
lstm_output = lstm_model.output
ensemble_output = Average()([cnn_output, lstm_output])

In [7]:
ensemble_model = Model(inputs=[cnn_model.input, lstm_model.input], outputs=ensemble_output)

In [8]:
ensemble_model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [9]:
# For the CNN model
cnn_input_shape = cnn_model.input_shape
print("CNN Model Input Shape:", cnn_input_shape)

# For the LSTM model
lstm_input_shape = lstm_model.input_shape
print("LSTM Model Input Shape:", lstm_input_shape)


CNN Model Input Shape: (None, 187, 2, 1)
LSTM Model Input Shape: (None, 187, 2, 1)


In [10]:
print("Ensemble Model Input Shape:", ensemble_model.input_shape)
print("Ensemble Model Output Shape:", ensemble_model.output_shape)

Ensemble Model Input Shape: [(None, 187, 2, 1), (None, 187, 2, 1)]
Ensemble Model Output Shape: (None, 5)


In [11]:
import numpy as np

# Create a sample input matching the input shape for both models
# For instance, a batch of 1 sample with shape (187, 2, 1)
sample_data = np.random.random((1, 187, 2, 1))

# Run a prediction to test the model
test_prediction = ensemble_model.predict([sample_data, sample_data])
print("Test Prediction Shape:", test_prediction.shape)
print("Test Prediction Output:", test_prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 448ms/step
Test Prediction Shape: (1, 5)
Test Prediction Output: [[9.9940324e-01 2.2245273e-04 2.2939642e-04 4.6542482e-05 9.8383513e-05]]


In [12]:
#The Ensembling Model is made Accurately

In [13]:
ensemble_model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 187, 2, 1) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 36, 1,     │      5,376 │ input_layer[0][0] │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 36, 1,     │      1,024 │ conv2d[0][0]      │
│ (BatchNormalizatio… │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ re_lu (ReLU)        │ (None, 36, 1,     │          0 │ batch_normalizat… │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 36, 1,     │          0 │ re_lu[0][0]       │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 32, 1,     │    655,872 │ dropout[0][0]     │
│                     │ 512)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 1,     │      2,048 │ conv2d_1[0][0]    │
│ (BatchNormalizatio… │ 512)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_1       │ (None, 187, 2, 1) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ re_lu_1 (ReLU)      │ (None, 32, 1,     │          0 │ batch_normalizat… │
│                     │ 512)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_5 (Conv2D)   │ (None, 36, 1,     │      5,376 │ input_layer_1[0]… │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 32, 1,     │          0 │ re_lu_1[0][0]     │
│                     │ 512)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 36, 1,     │      1,024 │ conv2d_5[0][0]    │
│ (BatchNormalizatio… │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_2 (Conv2D)   │ (None, 28, 1,     │  1,311,232 │ dropout_1[0][0]   │
│                     │ 512)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ re_lu_5 (ReLU)      │ (None, 36, 1,     │          0 │ batch_normalizat… │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 28, 1,     │      2,048 │ conv2d_2[0][0]    │
│ (BatchNormalizatio… │ 512)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_4 (Dropout) │ (None, 36, 1,     │          0 │ re_lu_5[0][0]     │
│                     │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ re_lu_2 (ReLU)      │ (None, 28, 1,     │          0 │ batch_normalizat

 Total params: 4,473,162 (17.06 MB)

 Trainable params: 4,467,658 (17.04 MB)

 Non-trainable params: 5,504 (21.50 KB)

In [14]:
import pandas as pd

train_df = pd.read_csv("mitbih_train.csv", header=None)
test_df = pd.read_csv("mitbih_test.csv", header=None)

In [15]:
print(train_df.head())
print(train_df.shape)

        0         1         2         3         4         5         6    \
0  0.977941  0.926471  0.681373  0.245098  0.154412  0.191176  0.151961   
1  0.960114  0.863248  0.461538  0.196581  0.094017  0.125356  0.099715   
2  1.000000  0.659459  0.186486  0.070270  0.070270  0.059459  0.056757   
3  0.925414  0.665746  0.541436  0.276243  0.196133  0.077348  0.071823   
4  0.967136  1.000000  0.830986  0.586854  0.356808  0.248826  0.145540   

        7         8         9    ...  178  179  180  181  182  183  184  185  \
0  0.085784  0.058824  0.049020  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.088319  0.074074  0.082621  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.043243  0.054054  0.045946  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.060773  0.066298  0.058011  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.089202  0.117371  0.150235  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   186  187  
0  0.0  0.0  
1  0.0  0.0  
2  0.0  0.0  
3  0.0  0.0 

In [16]:
import numpy as np

# Assuming the last column is the label
X_train = train_df.iloc[:, :-1].values  # Features
y_train = train_df.iloc[:, -1].values   # Labels

X_test = test_df.iloc[:, :-1].values
y_test = test_df.iloc[:, -1].values

# Reshape into (num_samples, 187, 2, 1)
X_train = X_train.reshape(-1, 187, 2, 1)
X_test = X_test.reshape(-1, 187, 2, 1)

In [17]:
# Example normalization (0 to 1 scaling)
X_train = X_train / 255.0
X_test = X_test / 255.0

In [18]:
# Run a prediction on the test data with the ensemble model
predictions = ensemble_model.predict([X_test, X_test])

# Display the predictions
print("Predictions:", predictions)

343/343 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step
Predictions: [[6.8685073e-01 4.5940073e-04 2.8753349e-01 1.8018985e-02 7.1373913e-03]
 [6.8703246e-01 4.5982271e-04 2.8738055e-01 1.7991446e-02 7.1356962e-03]
 [6.8714857e-01 4.5991340e-04 2.8726372e-01 1.7994871e-02 7.1329558e-03]
 ...
 [6.8555415e-01 4.5990237e-04 2.8882104e-01 1.7974239e-02 7.1906657e-03]
 [6.8657261e-01 4.5977131e-04 2.8780544e-01 1.8002566e-02 7.1596275e-03]
 [6.8578649e-01 4.6045787e-04 2.8856751e-01 1.7998759e-02 7.1868198e-03]]


In [19]:
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_test: (10946, 187, 2, 1)
Shape of y_test: (21892,)


In [20]:
# Assuming the last column in your CSV is the label
X_test = test_df.iloc[:, :-1].values  # All columns except the last one for features
y_test = test_df.iloc[:, -1].values   # Only the last column for labels

In [21]:
# If y_test has twice as many samples, try slicing it to match X_test
y_test = y_test[:X_test.shape[0]]

In [22]:
from tensorflow.keras.utils import to_categorical

# Convert integer labels to one-hot encoding, if necessary
y_test = to_categorical(y_test)

In [23]:
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_test: (21892, 187)
Shape of y_test: (21892, 5)


In [24]:
# Reshape X_test to (21892, 187, 2, 1)
X_test_reshaped = X_test.reshape(-1, 187, 2, 1)

In [25]:
print("Shape of X_test_reshaped:",X_test_reshaped.shape)

Shape of X_test_reshaped: (10946, 187, 2, 1)


In [26]:
# Trim y_test to match the number of samples in X_test
y_test_trimmed = y_test[:X_test.shape[0]]


In [27]:
y_test_trimmed.shape

(21892, 5)

In [28]:
print("Shape of y_test_trimmed:",y_test_trimmed.shape)

Shape of y_test_trimmed: (21892, 5)


In [29]:
# Trim y_test_trimmed to match the number of samples in X_test_reshaped
y_test_trimmed = y_test[:X_test_reshaped.shape[0]]

In [30]:
print("Shape of y_test_trimmed:",y_test_trimmed.shape)

Shape of y_test_trimmed: (10946, 5)


In [31]:
# Evaluate the model using reshaped X_test and trimmed y_test
loss, accuracy = ensemble_model.evaluate([X_test_reshaped, X_test_reshaped], y_test_trimmed)

# Print the results
print(f"Test Loss: {loss}")
print(f"Test Accuracy: {accuracy}")


343/343 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - accuracy: 0.9997 - loss: 0.0862
Test Loss: 0.09371625632047653
Test Accuracy: 0.9990864396095276


In [32]:
ensemble_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [33]:
result = ensemble_model.evaluate([X_test_reshaped, X_test_reshaped], y_test_trimmed)
print("Evaluation result:", result)

343/343 ━━━━━━━━━━━━━━━━━━━━ 17s 47ms/step - accuracy: 0.9997 - loss: 0.0862
Evaluation result: [0.09371625632047653, 0.9990864396095276]


In [34]:
# Evaluate the model using reshaped X_test and trimmed y_test
loss, accuracy = ensemble_model.evaluate([X_test_reshaped, X_test_reshaped], y_test_trimmed)

print(f"Test Accuracy: {accuracy}")


343/343 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.9997 - loss: 0.0862
Test Accuracy: 0.9990864396095276


In [35]:
x=accuracy

In [36]:
x=round(accuracy*100,2) #0.05 is outlier

In [37]:
print(f"Test Accuracy: {x}%")

Test Accuracy: 99.91%
